const SPOTIFY_AUTH_URL = 'https://accounts.spotify.com/authorize';
const SPOTIFY_TOKEN_URL = 'https://accounts.spotify.com/api/token';
const SPOTIFY_API = 'https://api.spotify.com/v1';
const SCOPES = 'playlist-modify-public playlist-modify-private';

function getRedirectUri(): string {
  // Explicit override wins — set this in Vercel / any other host's env vars
  if (process.env.SPOTIFY_REDIRECT_URI) return process.env.SPOTIFY_REDIRECT_URI;

  // Replit deployment
  if (process.env.REPLIT_DOMAINS) {
    const primary = process.env.REPLIT_DOMAINS.split(',')[0].trim();
    return `https://${primary}/callback`;
  }

  // Vercel preview / production deployments
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}/callback`;

  return 'http://localhost:5000/callback';
}

// In-memory store for pending OAuth states (keyed by random state string)
interface PendingExport {
  playlistName: string;
  tracks: Array<{ title: string; artist: string }>;
  expiresAt: number;
}
const pendingExports = new Map<string, PendingExport>();

export function buildSpotifyAuthUrl(state: string): string {
  const params = new URLSearchParams({
    client_id: process.env.SPOTIFY_CLIENT_ID!,
    response_type: 'code',
    redirect_uri: getRedirectUri(),
    scope: SCOPES,
    state,
    show_dialog: 'false',
  });
  return `${SPOTIFY_AUTH_URL}?${params}`;
}

export function storeExportState(
  state: string,
  playlistName: string,
  tracks: Array<{ title: string; artist: string }>
) {
  // Clean up expired entries
  const now = Date.now();
  for (const [key, val] of pendingExports) {
    if (val.expiresAt < now) pendingExports.delete(key);
  }
  pendingExports.set(state, { playlistName, tracks, expiresAt: now + 10 * 60 * 1000 });
}

export function consumeExportState(state: string): PendingExport | null {
  const data = pendingExports.get(state);
  if (!data || data.expiresAt < Date.now()) {
    pendingExports.delete(state);
    return null;
  }
  pendingExports.delete(state);
  return data;
}

async function exchangeCodeForToken(code: string): Promise<string> {
  const credentials = Buffer.from(
    `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`
  ).toString('base64');

  const res = await fetch(SPOTIFY_TOKEN_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization: `Basic ${credentials}`,
    },
    body: new URLSearchParams({
      grant_type: 'authorization_code',
      code,
      redirect_uri: getRedirectUri(),
    }).toString(),
  });

  const data = await res.json();
  if (!res.ok) {
    throw new Error(`Token exchange failed: ${data.error_description || data.error}`);
  }
  return data.access_token;
}

async function spotifyRequest(accessToken: string, method: string, path: string, body?: object) {
  const res = await fetch(`${SPOTIFY_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json();
  if (!res.ok) throw new Error(`Spotify API error on ${path}: ${JSON.stringify(data.error)}`);
  return data;
}

async function findTrackUri(
  accessToken: string,
  title: string,
  artist: string
): Promise<string | null> {
  // Strict search first
  try {
    const q = `track:${title} artist:${artist}`;
    const data = await spotifyRequest(
      accessToken,
      'GET',
      `/search?q=${encodeURIComponent(q)}&type=track&limit=1`
    );
    if (data?.tracks?.items?.length > 0) return data.tracks.items[0].uri;
  } catch {}

  // Loose search fallback
  try {
    const q = `${title} ${artist}`;
    const data = await spotifyRequest(
      accessToken,
      'GET',
      `/search?q=${encodeURIComponent(q)}&type=track&limit=1`
    );
    if (data?.tracks?.items?.length > 0) return data.tracks.items[0].uri;
  } catch {}

  return null;
}

export interface ExportResult {
  playlistUrl: string;
  tracksAdded: number;
  tracksFailed: number;
  failedTracks: string[];
}

export async function exportToSpotify(
  code: string,
  playlistName: string,
  tracks: Array<{ title: string; artist: string }>
): Promise<ExportResult> {
  const accessToken = await exchangeCodeForToken(code);

  // Create an empty playlist for the authenticated user
  const playlist = await spotifyRequest(
    accessToken,
    'POST',
    `/me/playlists`,
    {
      name: playlistName,
      description: 'Generated by MoodMusic Playlist Maker',
      public: false,
    }
  );

  // Search for each track and collect URIs
  const uris: string[] = [];
  const failedTracks: string[] = [];

  for (const track of tracks) {
    const uri = await findTrackUri(accessToken, track.title, track.artist);
    if (uri) {
      uris.push(uri);
    } else {
      failedTracks.push(`${track.title} – ${track.artist}`);
      console.log(`[Spotify] Not found: "${track.title}" by ${track.artist}`);
    }
  }

  // Add tracks (Spotify limit: 100 per request)
  // Endpoint renamed from /tracks to /items in Spotify's Feb 2026 API update
  for (let i = 0; i < uris.length; i += 100) {
    await spotifyRequest(accessToken, 'POST', `/playlists/${playlist.id}/items`, {
      uris: uris.slice(i, i + 100),
    });
  }

  return {
    playlistUrl: playlist.external_urls.spotify,
    tracksAdded: uris.length,
    tracksFailed: failedTracks.length,
    failedTracks,
  };
}
