import { useState } from "react";
import { usePlaylist } from "@/context/PlaylistContext";
import { Button } from "@/components/ui/button";
import { formatDuration, calculateTotalDuration } from "@/lib/utils";
import { Download, Share, Loader2, Music, Pencil, Check, X } from "lucide-react";
import { SiSpotify } from "react-icons/si";
import { useToast } from "@/hooks/use-toast";

export default function PlaylistResultStep() {
  const { playlistContext, playlistTracks, removeTrack, playlistName, setPlaylistName, playlistWarnings, setCurrentStep, startOver } = usePlaylist();
  const [isEditingName, setIsEditingName] = useState(false);
  const [editedName, setEditedName] = useState('');
  const { toast } = useToast();

  const handleDownload = () => {
    // Create a text representation of the playlist
    const playlistText = `${playlistName}\n\n${playlistContext}\n\n` + 
      playlistTracks.map((track, i) => 
        `${i+1}. ${track.title} - ${track.artist}`
      ).join('\n');
    
    // Create a blob and download it
    const blob = new Blob([playlistText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${playlistName.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    const header = `🎵 ${playlistName}\n${playlistContext}\n\n`;
    const trackList = playlistTracks
      .map((t, i) => `${i + 1}. ${t.title} — ${t.artist}`)
      .join('\n');
    const footer = `\n\nGenerated by MoodMusic Playlist Maker`;
    navigator.clipboard.writeText(header + trackList + footer);
    toast({
      title: "Playlist copied!",
      description: "Full track list copied to clipboard — paste it anywhere to share."
    });
  };
  
  const [isExporting, setIsExporting] = useState(false);
  const [spotifyPlaylistUrl, setSpotifyPlaylistUrl] = useState<string | null>(null);

  const exportToSpotify = async () => {
    setIsExporting(true);
    setSpotifyPlaylistUrl(null);

    // Open the popup IMMEDIATELY while we still have the user-gesture context,
    // so browsers don't block it. Show a loading screen until we have the auth URL.
    const width = 500, height = 700;
    const left = window.screenX + (window.outerWidth - width) / 2;
    const top = window.screenY + (window.outerHeight - height) / 2;
    const popup = window.open('', 'spotify-auth', `width=${width},height=${height},left=${left},top=${top}`);

    if (!popup) {
      setIsExporting(false);
      toast({
        title: 'Popup blocked',
        description: 'Please allow popups for this site and try again.',
        variant: 'destructive',
      });
      return;
    }

    // Show a loading screen with bouncing music notes while we fetch the auth URL
    popup.document.write(`<!DOCTYPE html>
<html>
<head>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #191414; color: white; display: flex; align-items: center;
         justify-content: center; height: 100vh; font-family: sans-serif; text-align: center; }
  .notes { display: flex; gap: 12px; justify-content: center; margin-bottom: 20px; }
  .note { font-size: 32px; animation: bounce 0.8s ease-in-out infinite; }
  .note:nth-child(1) { animation-delay: 0s; }
  .note:nth-child(2) { animation-delay: 0.15s; }
  .note:nth-child(3) { animation-delay: 0.3s; }
  .note:nth-child(4) { animation-delay: 0.45s; }
  @keyframes bounce {
    0%, 100% { transform: translateY(0); opacity: 0.5; }
    50%       { transform: translateY(-16px); opacity: 1; }
  }
  p { color: #B3B3B3; font-size: 15px; animation: pulse 1.5s ease-in-out infinite; }
  @keyframes pulse { 0%, 100% { opacity: 0.6; } 50% { opacity: 1; } }
</style>
</head>
<body>
  <div>
    <div class="notes">
      <span class="note">♩</span>
      <span class="note">♪</span>
      <span class="note">♫</span>
      <span class="note">♬</span>
    </div>
    <p>Connecting to Spotify…</p>
  </div>
</body>
</html>`);

    try {
      const res = await fetch('/api/spotify/initiate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          playlistName,
          tracks: playlistTracks.map(t => ({ title: t.title, artist: t.artist })),
        }),
      });

      if (!res.ok) {
        popup.close();
        const err = await res.json();
        throw new Error(err.message || 'Failed to start Spotify export');
      }

      const { authUrl } = await res.json();

      // Navigate the already-open popup to the Spotify auth page
      popup.location.href = authUrl;

      const cleanup = (interval: ReturnType<typeof setInterval>, timeout: ReturnType<typeof setTimeout>) => {
        clearInterval(interval);
        clearTimeout(timeout);
        window.removeEventListener('message', handleMessage);
        setIsExporting(false);
      };

      const handleMessage = (event: MessageEvent) => {
        if (typeof event.data !== 'object' || event.data === null) return;
        if (!('success' in event.data)) return;
        const data = event.data;
        cleanup(pollClosed, safetyTimeout);

        if (data.success) {
          setSpotifyPlaylistUrl(data.playlistUrl);
          toast({
            title: 'Playlist created on Spotify!',
            description: `${data.tracksAdded} tracks added${data.tracksFailed > 0 ? ` (${data.tracksFailed} not found on Spotify)` : ''}.`,
          });
        } else {
          toast({
            title: 'Spotify export failed',
            description: data.error || 'Something went wrong. Please try again.',
            variant: 'destructive',
          });
        }
      };

      window.addEventListener('message', handleMessage);

      // Reset if popup is closed without completing
      const pollClosed = setInterval(() => {
        if (popup.closed) cleanup(pollClosed, safetyTimeout);
      }, 500);

      // Safety net: always reset after 3 minutes
      const safetyTimeout = setTimeout(() => {
        cleanup(pollClosed, safetyTimeout);
      }, 3 * 60 * 1000);

    } catch (err: any) {
      setIsExporting(false);
      toast({
        title: 'Export failed',
        description: err.message || 'Could not export to Spotify.',
        variant: 'destructive',
      });
    }
  };

  return (
    <>
      <div className="playlist-header bg-gradient-to-b from-gray-800 to-[#191414] p-6">
        <div className="flex flex-col md:flex-row items-center">
          <div className="playlist-cover shadow-lg w-48 h-48 flex-shrink-0 mb-4 md:mb-0 md:mr-6">
            <div className="playlist-card w-full h-full rounded-lg flex items-center justify-center" 
                 style={{ background: 'linear-gradient(145deg, #191414, #252525)' }}>
              <div className="w-24 h-24 rounded-full bg-[#1DB954] flex items-center justify-center">
                <Music className="w-12 h-12 text-white" />
              </div>
            </div>
          </div>
          <div className="flex-1 text-center md:text-left">
            <p className="uppercase tracking-widest text-xs text-[#B3B3B3] mb-1">CUSTOM PLAYLIST</p>
            {isEditingName ? (
              <div className="flex items-center gap-2 mb-2">
                <input
                  autoFocus
                  className="text-2xl md:text-4xl font-bold bg-transparent border-b-2 border-[#1DB954] outline-none text-white w-full"
                  value={editedName}
                  onChange={e => setEditedName(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === 'Enter') {
                      setPlaylistName(editedName.trim() || playlistName);
                      setIsEditingName(false);
                    } else if (e.key === 'Escape') {
                      setIsEditingName(false);
                    }
                  }}
                />
                <button
                  onClick={() => {
                    setPlaylistName(editedName.trim() || playlistName);
                    setIsEditingName(false);
                  }}
                  className="text-[#1DB954] hover:text-white transition-colors flex-shrink-0"
                  aria-label="Save name"
                >
                  <Check className="w-6 h-6" />
                </button>
              </div>
            ) : (
              <div className="flex items-center gap-2 mb-2 group">
                <h2 className="text-2xl md:text-4xl font-bold">{playlistName}</h2>
                <button
                  onClick={() => { setEditedName(playlistName); setIsEditingName(true); }}
                  className="text-[#B3B3B3] hover:text-[#1DB954] transition-colors opacity-0 group-hover:opacity-100"
                  aria-label="Edit playlist name"
                >
                  <Pencil className="w-5 h-5" />
                </button>
              </div>
            )}
            <p className="text-[#B3B3B3] mb-4">
              {playlistContext}
            </p>
            <div className="text-sm text-[#B3B3B3]">
              <span>{playlistTracks.length} songs</span>
              <span className="mx-2">•</span>
              <span>{calculateTotalDuration(playlistTracks)}</span>
            </div>
          </div>
        </div>
      </div>
      
      <div className="playlist-tracks p-6">
        <div className="playlist-tracks-header flex justify-between text-xs uppercase tracking-wider text-[#B3B3B3] border-b border-gray-800 pb-2 mb-2 font-medium">
          <div className="flex-1"># Title</div>
          <div className="flex-1 text-left">Artist</div>
          <div className="hidden md:flex w-16 text-left">Time</div>
          <div className="hidden md:block w-7 flex-shrink-0" />
        </div>
        
        <div className="playlist-tracks-list">
          {playlistTracks.map((track, index) => (
            <div 
              key={track.id} 
              className="playlist-item flex items-center py-3 px-2 rounded group hover:bg-[rgba(255,255,255,0.1)]"
              style={{
                backgroundColor: index % 2 === 0 ? 'rgba(255, 255, 255, 0.03)' : 'transparent'
              }}
            >
              <div className="flex-1 flex items-center">
                <span className="mr-4 text-[#B3B3B3] w-4 text-right">{index + 1}</span>
                <div>
                  {track.url ? (
                    <a
                      href={track.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-medium hover:text-[#1DB954] hover:underline transition-colors"
                    >
                      {track.title}
                    </a>
                  ) : (
                    <div className="font-medium">{track.title}</div>
                  )}
                  {track.album && (
                    <div className="text-xs text-[#B3B3B3] hidden md:block">Album: {track.album}</div>
                  )}
                </div>
              </div>
              <div className="flex-1 text-left text-[#B3B3B3]">{track.artist}</div>
              <div className="hidden md:block w-16 text-left text-[#B3B3B3]">
                {formatDuration(track.duration)}
              </div>
              <button
                onClick={() => removeTrack(track.id)}
                className="ml-3 text-[#B3B3B3] hover:text-red-400 transition-colors opacity-0 group-hover:opacity-100 flex-shrink-0"
                aria-label="Remove track"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          ))}
        </div>

        {/* Seed song warnings (zero similar tracks / possible typo) */}
        {playlistWarnings.length > 0 && playlistWarnings.map((w, i) => {
          const wasAutoFixed = w.message.startsWith('We used');
          return (
            <div key={i} className={`mt-4 mx-2 flex items-start gap-2 rounded-lg border px-4 py-3 text-sm ${
              wasAutoFixed
                ? 'border-blue-600/40 bg-blue-900/20 text-blue-300'
                : 'border-orange-600/40 bg-orange-900/20 text-orange-300'
            }`}>
              <span className="mt-0.5 text-base leading-none flex-shrink-0">{wasAutoFixed ? 'ℹ️' : '⚠️'}</span>
              <span>{w.message}</span>
            </div>
          );
        })}

        {/* Short playlist hint */}
        {playlistTracks.length < 20 && (
          <div className="mt-4 mx-2 flex items-start gap-2 rounded-lg border border-yellow-600/40 bg-yellow-900/20 px-4 py-3 text-sm text-yellow-300">
            <span className="mt-0.5 text-base leading-none">💡</span>
            <span>
              Only {playlistTracks.length} songs matched your criteria. For a longer playlist, try adding more example songs.
            </span>
          </div>
        )}
      </div>

      <div className="px-6 pb-6">
        <div className="flex flex-col space-y-4">
          {/* Edit Prompts button — returns to step 2 with data intact */}
          <Button 
            onClick={() => setCurrentStep(2)}
            className="w-full md:w-auto bg-gray-700 hover:bg-gray-600 text-white px-6 py-3 rounded-full font-medium transition duration-200 h-auto"
          >
            Edit Prompts
          </Button>
          
          {/* Export buttons */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {/* Spotify Export / Open in Spotify */}
            {spotifyPlaylistUrl ? (
              <>
                <style>{`
                  @keyframes spotifyGlow {
                    0%, 100% { box-shadow: 0 4px 12px rgba(29,185,84,0.5); }
                    50%       { box-shadow: 0 0 28px 8px rgba(29,185,84,0.85); }
                  }
                  .spotify-open-btn { animation: spotifyGlow 1.6s ease-in-out infinite; }
                `}</style>
                <a
                  href={spotifyPlaylistUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="spotify-open-btn w-full px-6 py-3 rounded-full font-medium flex items-center justify-center h-auto text-white order-first"
                  style={{ background: "linear-gradient(45deg, #1DB954, #1ed760)" }}
                >
                  <SiSpotify className="w-5 h-5 mr-2" />
                  Open in Spotify
                </a>
              </>
            ) : (
              <div className="flex flex-col gap-1">
                <Button
                  onClick={exportToSpotify}
                  disabled={isExporting}
                  className="w-full px-6 py-3 rounded-full font-medium transition duration-200 flex items-center justify-center h-auto text-white disabled:opacity-70"
                  style={{
                    background: "linear-gradient(45deg, #1DB954, #1ed760)",
                    boxShadow: "0 4px 12px rgba(29, 185, 84, 0.5)"
                  }}
                >
                  {isExporting ? (
                    <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                  ) : (
                    <SiSpotify className="w-5 h-5 mr-2" />
                  )}
                  {isExporting ? "Connecting to Spotify…" : "Export to Spotify"}
                </Button>
                <p className="text-[10px] text-[#B3B3B3] text-center leading-tight px-1">
                  Direct export is limited to pre-authorized accounts — Spotify's API restricts developer apps to a small whitelist. Use <span className="text-white">Download</span> to save a track list and add songs manually.
                </p>
              </div>
            )}
            
            {/* Download Button */}
            <Button
              onClick={handleDownload}
              className="w-full bg-gray-700 hover:bg-gray-600 text-white px-6 py-3 rounded-full font-medium transition duration-200 flex items-center justify-center h-auto"
            >
              <Download className="w-5 h-5 mr-2" />
              Download
            </Button>
            
            {/* Share Button */}
            <Button
              onClick={handleShare}
              className="w-full bg-gray-700 hover:bg-gray-600 text-white px-6 py-3 rounded-full font-medium transition duration-200 flex items-center justify-center h-auto"
            >
              <Share className="w-5 h-5 mr-2" />
              Share
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}
